.github/CODEOWNERS, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Add...
* Github issue template
* Github pull request template
* Code owner config
Governance.
=> Add github configurations

.circleci/config.yml, go.mod, go.sum
=> Add goreleaser

.circleci/config.yml, README.md
=> Remove v from tag

.circleci/config.yml
=> Fix goreleaser

.circleci/config.yml
=> Use executer for CI

.circleci/config.yml
=> Add test for release

.circleci/config.yml
=> Remove require

.circleci/config.yml
=> Upgrade to 1.14

spinnaker/provider.go
As title.
Because the CI job failed.
=> Format Spinnaker provider

.circleci/config.yml
As title.
Tests on push wasn't working as expected.
=> Seperate CI job for test and release

.circleci/config.yml
=> Remove "main" level in workflow

.circleci/config.yml
=> Change missing "build" job to "test"

CHANGELOG.md
As title.
For changelog management.
=> Add log for application permission

CHANGELOG.md, ROADMAP.md, docs/data-resources/project.html.md, docs/resources/application.html.md, docs/resources/project.html.md, spinnaker/api/application.go, spinnaker/api/project.go, spinnaker/data_source_spinnaker_application.go, spinnaker/data_source_spinnaker_project.go, spinnaker/provider.go, spinnaker/resource_application.go, spinnaker/resource_project.go, spinnaker/resource_project_test.go
As title.
To configure projects.
=> Add "spinnaker_project" resource/data source

docs/resources/application.html.md, spinnaker/resource_application.go
As title.
Add deprecated field to safely migrated from `0.1.0`.
=> add(spinnaker): deprecated fields for spinnaker_application

spinnaker/resource_application.go
=> format resource application

.circleci/config.yml
As title.
The CI Job for test is broken for PRs.
=> fix broken CI for PR

.github/workflows/test-provider.yml
=> change(.github): test to test-provider

.github/workflows/release-provider.yml
As title.
To release this provider on tag push.
=> add(.github): release workflow

.github/workflows/release-provider.yml, .github/workflows/test-provider.yml
As title.
I want to separate the test and release workflow by events.
=> fix(.github): release flow

.github/workflows/test-provider.yml
As title.
It should test when merge.
=> fix(.github): test condition

CHANGELOG.md, ROADMAP.md
As title.
Prepare for the release of `0.2.0`.
=> add(changelog): release notes for 0.2.0

.github/workflows/release-provider.yml
As title.
To sign the release with the GPG key.
=> add(.github): gpg workflow

.goreleaser.yml
As title.
* We don't want to make draft.
* We want to add changelogs.
=> fix(gorelease): release and changelog

.goreleaser.yml
As title.
`tar.gz` is missing.
=> add(goreleaser): targz

CHANGELOG.md
As title. Add datetime.
To release `0.2.1`.
=> Update release 0.2.1 changelog

README.md
=> Remove "the" grammer mistake

.github/workflows/release-provider.yml, CHANGELOG.md
=> Fix release tagging

CHANGELOG.md
As title.
Release `v0.2.2` provider.
=> Update document for v0.2.2

.github/workflows/release-provider.yml
As title.
Improves https://github.com/mercari/terraform-provider-spinnaker/pull/59
=> Remove no need `-xxx` tagging

.goreleaser.yml, CHANGELOG.md
As title.
Because the release was broken.
=> Fix broken zip output by goreleaser

CHANGELOG.md
To release `v0.2.4`.
This contains tiny changes that I've self-reviewed and merged too. PTAL.
Maintain 🚀
=> Update release notes for v0.2.4

.dependabot/config.yml, .github/dependabot.yml
=> Migrate dependabot to v2 from v1

.github/workflows/release-provider.yml, .goreleaser.yml, CHANGELOG.md
As title.
Because we missed in the previous PR 👍
=> Port goreleaser.yml config

spinnaker/resource_pipeline_test.go
Add tests for resource_pipeline.
Pipeline resource should also have tests.
=> add tests for resource_pipeline

spinnaker/resource_pipeline.go, spinnaker/resource_pipeline_test.go
Support for resource pipeline import.
Importing spinnaker pipeline resources should be supported.
Fixes https://github.com/mercari/terraform-provider-spinnaker/issues/71
=> Resource pipeline import
